#!/usr/bin/env bash
# Strata Enterprise — Environment Generator
#
# Usage:
#   curl -fsSL https://strata.do/server/env.sh | bash
#   curl -fsSL https://strata.do/server/env.sh | bash -s -- ./.env

set -euo pipefail

target="${1:-./.env}"
mkdir -p "$(dirname "$target")"

strata_secret_key_base="$(openssl rand -hex 64)"
strata_encryption_primary_key="$(openssl rand -hex 16)"
strata_encryption_deterministic_key="$(openssl rand -hex 16)"
strata_encryption_key_derivation_salt="$(openssl rand -hex 16)"

cat > "$target" << ENV_EOF
# Strata Server Environment Template

# ===================================================================
# Required: License and Database Connectivity
# ===================================================================

# License token provided by Strata.
LICENSE_KEY=replace_with_license_key

# PostgreSQL connection used by Strata (primary, queue, cache, cable DBs).
DB_HOST=replace_with_db_host
DB_PORT=5432
DB_USERNAME=replace_with_db_username
DB_PASSWORD=replace_with_db_password

# ===================================================================
# Required: Strata Encryption and Signing Secrets
# ===================================================================

# 128 hex chars. Auto-generated by env.sh.
STRATA_SECRET_KEY_BASE=${strata_secret_key_base}

# Each is 32 hex chars. Auto-generated by env.sh.
STRATA_ENCRYPTION_PRIMARY_KEY=${strata_encryption_primary_key}
STRATA_ENCRYPTION_DETERMINISTIC_KEY=${strata_encryption_deterministic_key}
STRATA_ENCRYPTION_KEY_DERIVATION_SALT=${strata_encryption_key_derivation_salt}

# ===================================================================
# Common Application Settings
# ===================================================================

# Public hostname and protocol used for generated URLs.
# APP_HOST=localhost
# APP_PROTOCOL=http
# Host port exposed by docker compose (maps to container STRATA_CONTAINER_PORT).
# PORT=3000

# Container HTTP listen port for Strata runtime (default: 80).
# STRATA_CONTAINER_PORT=80

# SSL behavior behind reverse proxy / load balancer.
# ASSUME_SSL=false
# FORCE_SSL=false

# Logging level (debug, info, warn, error, fatal).
# RAILS_LOG_LEVEL=info

# Image tag to run; pin in production (avoid relying only on latest).
# STRATA_VERSION=latest

# ===================================================================
# Optional: File Storage Backend
# ===================================================================

# local | amazon | google | microsoft
# STORAGE_BACKEND=local

# Add provider-specific variables when using non-local storage backends.
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_REGION=
# S3_BUCKET=
# S3_ENDPOINT=
ENV_EOF

echo "[strata] Wrote environment file to $target"
